site_name: Computer Engineering (CE) 

theme: 
  #name: 'readthedocs'
  name: 'material'
  custom_dir: 'custom_theme/'
  features:
    - navigation.tabs
    - content.code.annotate
    - content.code.copy


plugins:
  #- info
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags:
      tag_file: tags.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - index: index.md
  - 'ch02':
    - 'Building Hardware for Bits':
      - 'CE/ce02_03_0_HW4Bits.md'
      - 'relay': 'CE/ce02_03_1_relay.md'
      - 'vacuum tube': 'CE/ce02_03_2_vacuum_tube.md'
      - 'transistor': 'CE/ce02_03_3_transistor.md'
      - 'IC': 'CE/ce02_03_4_IC.md'
    - 'Gates':
      - 'Gate에 대해서': 'CE/ce02_04_0_gate.md'
      - 'Noise와 싸우기': 'CE/ce02_04_1_glitch.md'
      - 'Propagation Delay': 'CE/ce02_04_3_propagation_delay.md'
      - 'CE/ce02_04_4_0_gate_outputs.md'
      - 'Totem-pole Output': 'CE/ce02_04_4_1_totem_pole_output.md'
      - 'Open-Collector Output': 'CE/ce02_04_4_2_open_collector.md'
      - 'Tri-State Output': 'CE/ce02_04_4_3_tri_state_output.md'
  - 'os':
    - 'kernel.md'
  - Material Test:
    - code blk: test_code_blocks.md
  - tags: tags.md
