site_name: BME228 

theme: 
  #name: 'readthedocs'
  name: 'material'
  logo: 'assets/MMMIL_logo.jpg'
  custom_dir: 'custom_theme/'
  features:
    - navigation.tabs
    - content.code.annotate
    - content.code.copy


plugins:
  #- info
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags:
      tag_file: tags.md
  #- glightbox

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables


nav:
  - index: index.md
  - 'CE':
    - 'ch00 : Introduction' : 
      - 'CE/ch00/computer.md'
      - 'CE/ch00/history_of_computers.md'
      - 'CE/ch00/category_of_computers.md'
      - 'CE/ch00/component_of_computer.md'
    - 'ch01: Representation of Data':
      - "CE/ch01/ch01_00_data_representation.md"
      - "CE/ch01/ch01_01_information.md"
      - "Bits and Boolean Algebra":
        - "CE/ch01/ch01_10_bit.md"
        - "CE/ch01/ch01_11_msb_and_lsb.md"
        - "CE/ch01/ch01_12_otherunits.md"
        - "CE/ch01/ch01_13_boolean_algebra.md"
        - "CE/ch01/ch01_14_prefix.md"
      - "Bits and Number":
        - "CE/ch01/numeral_system.md"
        - "CE/ch01/positive_number.md"
        - "CE/ch01/negative_number.md"
        - "CE/ch01/overflow_underflow.md"
        - "CE/ch01/real_number.md"
        - "CE/ch01/code_for_numbers.md"
      - "Bits and Character":
        - "CE/ch01/code_for_character.md"
        - "CE/ch01/Encoding_for_external_rep.md"
    - 'ch02: Bits and Combinatorial Logic':
      - 'Building Hardware for Bits':
        - 'CE/ch02_co/ce02_03_0_HW4Bits.md'
        - 'relay': 'CE/ch02_co/ce02_03_1_relay.md'
        - 'vacuum tube': 'CE/ch02_co/ce02_03_2_vacuum_tube.md'
        - 'transistor': 'CE/ch02_co/ce02_03_3_transistor.md'
        - 'IC': 'CE/ch02_co/ce02_03_4_IC.md'
      - 'Gates':
        - 'Gate에 대해서': 'CE/ch02_co/ce02_04_0_gate.md'
        - 'Noise와 싸우기': 'CE/ch02_co/ce02_04_1_glitch.md'
        - 'Propagation Delay': 'CE/ch02_co/ce02_04_3_propagation_delay.md'
        - 'CE/ch02_co/ce02_04_4_0_gate_outputs.md'
        - 'Totem-pole Output': 'CE/ch02_co/ce02_04_4_1_totem_pole_output.md'
        - 'Open-Collector Output': 'CE/ch02_co/ce02_04_4_2_open_collector.md'
        - 'Tri-State Output': 'CE/ch02_co/ce02_04_4_3_tri_state_output.md'
      - 'Adder, Encoder, and Mux': 
        - 'CE/ch02_co/ce02_05_0_adder_encoder_demux.md'
        - 'CE/ch02_co/ce02_05_1_adder.md'
    - 'ch03: Memory and Sequential Logic':
      - 'time and memory':
        - 'time and memory': 'CE/ch03_seq/ce03_01_0_0_memory0.md'
        - 'oscillator':      'CE/ch03_seq/ce03_01_0_1_Oscillator.md'
        - 'latch':           'CE/ch03_seq/ce03_01_0_2_latch.md'
        - 'flip-flop':       'CE/ch03_seq/ce03_01_0_3_flip_flop.md'
        - 'counter':         'CE/ch03_seq/ce03_01_0_4_counter.md'
        - 'register':        'CE/ch03_seq/ce03_01_0_5_register.md'
      - "Memory (and Storage)":
        - 'memory summary':  'CE/ch03_seq/ce03_02_0_primary_secondary_memory.md'
        - 'RAM and ROM':
          - 'memory 기초':  'CE/ch03_seq/ce03_02_1_memory1.md'
          - 'RAM':          'CE/ch03_seq/ce03_02_2_RAM.md'
          - 'ECC Memory':   'CE/ch03_seq/ce03_04_ecc_memory.md'
          - 'ROM':          'CE/ch03_seq/ce03_02_3_rom.md'
        - 'Block Device':   'CE/ch03_seq/ce03_02_block_device.md'
        - 'Flash Memory':   'CE/ch03_seq/ce03_03_flash_ssd.md'
      - "Etc":
        - 'HW vs SW':  'CE/ch03_seq/ce03_05_hw_and_sw.md'
    - 'ch04: Computer Structure':
      - "Memory and Bus":
        - "CE/ch04/ce04_01_memory.md"
        - "CE/ch04/ce04_02_byte_ordering.md"
        - "CE/ch04/ce04_03_io_bus.md"
      - "CPU":
        - "CE/ch04/ce04_04_cpu.md"
        - "CE/ch04/ce04_04_01_alu.md"
        - "CE/ch04/ce04_11.md"
        - "CE/ch04/ce04_22.md"
        - "CE/ch04/ce04_31.md"
      - "CE/ch04/ce04_41.md"
      - "CE/ch04/ce04_51.md"
    - 'ch05: Computer Architecture':
      - "CE/ch05/ch05_01_01.md"
      - "CE/ch05/ch05_02_01_function.md"
      - "CE/ch05/ch05_03_01.md"
      - "CE/ch05/ch05_04_02_interrupt.md"
      - "CE/ch05/ch05_05_01_idx_reg_rel_add.md"
      - "CE/ch05/ch05_06_01_mmu.md"
      - "CE/ch05/ch05_07_01_virtual_memory.md"
    - 'ch06':
      - "Data Transfer":
        - "IO Ports":         "CE/ch06/ce06_1_01_ioport.md"
        - "Push Btns":        "CE/ch06/ce06_1_02_push_button.md"
        - "FND":              "CE/ch06/ce06_1_03_fnd.md"
        - "IO Mux":           "CE/ch06/ce06_1_04_multiplexing_posts.md"
        - "Duty Cycle":       "CE/ch06/ce06_1_05_bright_duty.md"
        - "Gray Code":        "CE/ch06/ce06_1_06_graycode.md"
        - "Parallel Transfer": "CE/ch06/ce06_1_07_parallel_com.md"
        - "Serial Transfer":  "CE/ch06/ce06_1_08_serial_com.md"
        - "USB":              "CE/ch06/ce06_1_09_usb.md"
      - "Network and Communication":
        - "The History of Data Communication Network":  "CE/ch06/ce06_2_01_history.md"
        - "Ethernet, Router, Switch and so on":         "CE/ch06/ce06_2_02_Ethernet_Router_Switch.md"
        - "Internet and Related Protocols":             "CE/ch06/ce06_2_03_Internet.md"
      - "Human Interface Devices":
        - "CE/ch06/ce06_4_04_keyboard.md"
    - 'ch08 Programming Language and Language Processing':
      - "CE/ch08/ce08_programming_language.md"
      - "CE/ch08/ce08_high_low_level_language.md"
      - "CE/ch08/ce08_compiler_interpreter.md"
      - "CE/ch08/ce08_assembly_language.md"
    - 'ch09':
      - "CE/ch09/ce09_web_browser.md"
    - 'ch10':
      - "Concepts for Programming":
        - "Command Line Interface": "CE/ch10/ce10_2_01_cli_terminal.md"
        - "Standard I/O Library"  : "CE/ch10/ce10_2_04_stdio.md"
    - '작성중':
      - "CE/ch15/ce15_2_4_portability.md"
      - "CE/ch15/ce15_2_5_package_management.md"
      - "CE/ch15/ce15_2_6_container.md"
  - "os":
    - "OS/operating_system.md"
    - "OS/kernel.md"
    - "OS/console_terminal_shell_kernel.md"
    - "OS/UNIX.md"
    - "OS/LINUX.md"
    - "OS/file_folder_dir_cmd.md"
    - "OS/file.md"
    - "OS/folderNdirectory.md"
    - "OS/path.md"
    - "OS/disk_partition_volume.md"
    - "OS/linux_cmds.md"
    - "OS/windows_cmds.md"
  - "OOP":
    - "OOP and Programming Paradigm":
      - "python/oop/oop_0_00_OOP.md"
      - "python/oop/oop_0_01_Object.md"
      - "python/oop/oop_0_02_programming_paradigm.md"
      - "python/oop/oop_0_02_0imperative_declarative.md"
      - "python/oop/oop_0_03_oop_vs_structured.md"
    - "OOP Details":
      - "python/oop/oop_1_00_OOP_term.md"
      - "python/oop/oop_1_01_abstraction.md"
      - "python/oop/oop_1_001_modularity.md"
      - "python/oop/oop_1_02_encapsulation.md"
      - "python/oop/oop_1_03_inheritance.md"
      - "python/oop/oop_1_04_relationship.md"
      - "python/oop/oop_1_05_message_passing.md"
      - "python/oop/oop_1_07_polymorphism.md"
    - "OOP Etc":
      - "python/oop/ds_setter_and_getter.md"
    - "OOP Summary" : "python/oop/oop_2_00_OOP_summary.md"
    - "python":
      - "Python의 Class (차이점)": "python/oop/oop_3_01_python_class.md"
      - "Python의 Encapsulation": "python/oop/oop_3_02_python_encapsulation.md"
  - "Python":
    - "python/basic/module_package.md"
  - "DIP":
    - "OpenCV":
      - "Gui Features in OpenCV":
        - "DIP/cv2/ch00/dip_0_00.md"
        - "Note: color space": "DIP/cv2/ch00/dip_0_00_color_space.md"
        - "DIP/cv2/ch00/dip_0_02.md"
        - "DIP/cv2/ch00/dip_0_03.md"
        - "DIP/cv2/ch00/dip_0_04.md"
      - "Core Operations":
        - "DIP/cv2/ch01/dip_1_01.md"
        - "DIP/cv2/ch01/dip_1_02.md"
      - "Image Processing":
        - "DIP/cv2/ch00/dip_0_00_color_space.md"
        - "DIP/cv2/ch02/dip_thresholding.md"
        - "DIP/cv2/ch02/dip_histogram.md"
        - "DIP/cv2/ch02/dip_histogram_backprojection.md"
        - "Canny Edge Detection" : "DIP/ch02_02_01_canny.md"
        - "DIP/cv2/ch02/dip_pyramid.md"
        - "DIP/cv2/ch02/dip_contour_basic.md"
        - "DIP/cv2/ch02/dip_contour_features.md"
        - "DIP/cv2/ch02/dip_contour_properties.md"
        - "DIP/cv2/ch02/dip_low_pass_filter.md"
        - "DIP/cv2/ch02/dip_edge_detection_high_pass_filter.md"
        - "DIP/ch10_LoG.md"
        - "DIP/cv2/ch02/dip_geometric_transformation.md"
        - "DIP/cv2/ch02/dip_morphological_op.md"
        - "DIP/cv2/ch02/dip_hough_transform.md"
        - "DIP/cv2/ch02/dip_circle_hough_transform.md"
        - "DIP/cv2/ch02/dip_template_matching.md"
      - "etc":
        - "DIP/cv2/etc/floodfill.md"
        - "DIP/cv2/etc/dip_convolution.md"
        - "DIP/cv2/etc/dip_metrics.md"
    - "Image Feature":
      - "DIP/ch02_01_00_classical_cv.md"
      - "DIP/ch02_01_01_keypoints.md"
      - "DIP/ch02_01_02_simple_blob_detector.md"
      - "Old Style Features":
        - "DIP/ch02_02_01_canny.md"
        - "DIP/ch02_02_02_harris_corner.md"
      - "DIP/ch02_03_03_hog.md"
  - "ML":
    - "Introduction":
      - "ML/ch00/ch00_00_intro.md"
      - "ML/ch00/ch00_01_dartmouth_ai.md"
      - "ML/ch00/ch00_01_what_is_ml.md"
      - "ML/ch00/ch00_11_why_use_ml.md"
      - "ML/ch00/ch00_12_type_of_ml.md"
      - "ML/ch00/ch00_20_supervised.md"
      - "ML/ch00/ch00_21_unsupervised.md"
      - "ML/ch00/ch00_22_semisupervised.md"
      - "ML/ch00/ch00_23_reinforcement_learning.md"
      - "ML/ch00/ch00_24_feature_attribute.md"
      - "ML/ch00/ch00_31_instance_based_learning.md"
      - "ML/ch00/ch00_32_model_based_learning.md"
      - "ML/ch00/ch00_33_what_is_model.md"
      - "ML/ch00/ch00_41_online_learning.md"
      - "ML/ch00/ch00_42_batch_learning.md"
      - "ML/ch00/ch00_50.md"
    - "Ex : End_to_End Learning":
      - "ML/ch01/ch01_51.md"
      - "ML/ch01/ch01_52.md"
    - "Classification":
      - "ML/ch02/ml_cls_metrics.md"
      - "ML/ch02/ml_cls_types.md"
    - "Linear Regression and Logistic Regression":
      - "ML/ch03/logistic_regression.md"
    - "Ensemble Learning":
      - "ML/ch05/ml_stacking.md"
    - "Dimensionality Reduction":
      - "ML/ch06/ml_pca.md"
    - "Unsupervised Learning":
      - "ML/ch07/clustering.md"
      - "ML/ch07/manifold.md"
      - "ML/ch07/topological_space.md"
      - "ML/ch07/tSNE.md"
    - "Deep Learning (simple)":
      - "ML/ch08/dev_hist_ann.md"
      - "ML/ch08/back_propagation.md"
      - "ML/ch08/reverse_mode_autodiff.md"
      - "ML/ch08/datastructure_graph.md"
      - "ML/ch09/sol_gv_ge.md"
      - "ML/ch09/weight_initializations.md"
      - "ML/ch09/act_relu.md"
      - "ML/ch09/act_elu.md"
      - "ML/ch09/act_silu.md"
      - "ML/ch09/batch_normalization.md"
    - "Optimizers":
      - "ML/ch09/op_summary.md"
      - "ML/ch09/op_momentum.md"
      - "ML/ch09/op_nesterov.md"
      - "ML/ch09/op_adagrad.md"
      - "ML/ch09/op_rmsprop.md"
      - "ML/ch09/op_adam.md"
      - "ML/ch09/op_nadam.md"
    - "Transfer Learning":
      - "ML/ch11_training/knowledge_transfer.md"
    - "CNN":
      - "ML/ch14_cnn/CNN_intro.md"
      - "ML/ch14_cnn/LeNet-5.md"
      - "ML/ch14_cnn/alexnet.md"
    - "RNN":
      - "ML/ch16_RNN/RNN_intro.md"
      - "ML/ch16_RNN/RNN_memory_cell.md"
      - "ML/ch16_RNN/RNN_topologies.md"
      - "ML/ch16_RNN/RNN_Bahdanau_attention.md"
      - "ML/ch16_RNN/RNN_attention_score.md"
    - "GAN":
      - "ML/ch17_GM/GAN_intro.md"
    - "Colab":
      - "CE/colab/hw_spec.md"
      - "CE/colab/cells.md"
      - "CE/colab/hotkeys.md"
      - "CE/colab/gpu.md"
  - "SS":
    - "z-Transform":
      - "SS/ch08/ch08_33_z_t_time_shift.md"
  - Material Test:
    - code blk: test_code_blocks.md
  - tags: tags.md
